version: '3.3'

services:
  network-management:
    container_name: network-management
    image: namic:5000/network-management
    build: $PWD
    ports: 
      - "80:8081"
    volumes: 
      - $PWD/data/network_management/:/webapp
    depends_on:
      - postgres
      - mysql 
      - minion_worker    
    command: plackup -R lib bin -s Starman --workers=10 -p 8081 -a bin/app.psgi

  mysql:
    container_name: mysql
    image: kiels-laptop:5000/mysql
    environment:
      - MYSQL_DATABASES=network_management
      - MYSQL_ROOT_PASSWORD=Tripper
      - MYSQL_HOST=127.0.0.1
      - MYSQL_PORT=3306
      - MYSQL_USER=nm
      - MYSQL_PASSWORD=Tripper
      - MYSQL_MY_DATABASE=network_management
    volumes:
      - $PWD/data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  postgres:
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - "$PWD/postgres/data:/var/lib/postgresql"
    image: kiels-laptop:5000/postgres:9.6.3
    build: $PWD/postgres
    env_file:
      - db.env

  minion_worker: 
    container_name: minion_worker
    image: kiels-laptop:5000/minion_build
    build: $PWD/minion
    command: /data/wait-for-it.sh mysql:3306 -- /data/worker.pl
    volumes:
      - $PWD/minion/data:/data
    environment:
      CONNECTION_STRING: 'postgresql://mic:mic@postgres/mic'
      NUMBER_OF_JOBS: 12
    env_file:
      - db.env
    depends_on:
      - postgres
      - mysql
    tty: true

