postgres:
#  restart: always
  image: postgres
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false

    - DB_USER=kiel
    - DB_PASS=Tripper
    - DB_NAME=test
  volumes:
    - "$PWD/data/postgresql:/var/lib/postgresql"
